### ISSUE TITLE
Add importable constants for Chromosome, Start, End, etc.

### ISSUE THREAD

**Issue by dvmcconnell** [pyranges/pyranges#387]
Since pyranges expects specific names with specific casing for column names, it would be nice if there were importable constants for these values. Something like:

```python
import pandas as pd
import pyranges as pr

df = pd.DataFrame(columns=[pr.Chromosome, pr.Start, pr.End])
```

It would also be great if any columns with default values like `NumberOverlaps` coming from `count_overlaps` had constants for them. Just feels a bit weird having to create constants in your own code for values that are being used in an external package.

**Comment by marco-mariotti** [comment]
Thanks @dvmcconnell !
Indeed, the next version of pyranges, V1, has exactly what you mention: https://github.com/pyranges/pyranges_1.x/blob/master/pyranges/core/names.py

E.g.
`from pyranges.core.names import CHROM_COL`

V1 will replace the current version later this year. We're taking things slow because it's a major change in data structure that necessarily breaks backwards compatibility. I encourage you to adopt V1 early, see https://pyranges1.readthedocs.io/en/latest/, including a guide for migration from v0 to v1

**Comment by dvmcconnell** [comment]
oh, perfect 👍 thanks!
